### ISSUE TITLE
Combo arazoa

### ISSUE THREAD

**Issue by Iker-elorrieta** [Iker-elorrieta/Erronka3T5#2]
https://github.com/Iker-elorrieta/Erronka3T5/blob/dc6f56f7ba82a4efbefed11a061a46efa59c19aa/Reto3_T5/src/Vista/Hasiera.java#L488
Frogatu honekin...ea zer gertatzen den...
public void actionPerformed(ActionEvent e) {
							Component[] compos = saioak.getComponents();
							for (int i = 0; i < compos.length; i++) {

								if (compos[i].getClass().equals(comboBox_sexua.getClass())) {
									JComboBox jC = (JComboBox) compos[i];
									System.out.println(jC.getSelectedIndex());
								}

							}
					
							String saio_aretoa = metodoak.SaioAretoak(id_filma, data_string,
									String.valueOf(comboBox_ordutegi.getSelectedItem()), saioak_array);
							lbl_areto.setText("");
							lbl_areto.setText(saio_aretoa);
						}

**Comment by IbaiAlvarez** [comment]
Frogatu dut kode hori aldatzen eta denbora guztian index 0 bueltatzen dit.
Horrela geratzen zait kodea:

public void actionPerformed(ActionEvent e) {
	Component[] compos = saioak.getComponents();
	for (int i = 0; i < compos.length; i++) {
		if (compos[i].getClass().equals(comboBox_sexua.getClass())) {
			JComboBox jC = (JComboBox) compos[i];
			System.out.println(jC.getSelectedIndex());
		}
	}
	String saio_aretoa = metodoak.SaioAretoak(id_filma, data_string,String.valueOf(comboBox_ordutegi.getSelectedItem()), saioak_array);	
        lbl_areto.setText("");
	lbl_areto.setText(saio_aretoa);	
}
